spring.application.name=sgp-backend
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/sgp
spring.datasource.username=root
spring.datasource.password=evelyne
